# Generated by Django 4.1.6 on 2023-02-08 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutemodel',
            name='courses',
        ),
        migrations.AddField(
            model_name='institutemodel',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_institutes', to='Course_app.coursemodel'),
        ),
    ]
